export const USER_PAGE_LOADED = 'USER_PAGE_LOADED';
export const SUBMIT_USER = 'SUBMIT_USER';
export const DELETE_USER = 'DELETE_USER';
export const SET_EDIT_USER = 'SET_EDIT_USER';
export const EDIT_USER = 'EDIT_USER';

export const VEHICULE_PAGE_LOADED = 'VEHICULE_PAGE_LOADED';
export const SUBMIT_VEHICULE = 'SUBMIT_VEHICULE';
export const DELETE_VEHICULE = 'DELETE_VEHICULE';
export const SET_EDIT_VEHICULE = 'SET_EDIT_VEHICULE';
export const EDIT_VEHICULE = 'EDIT_VEHICULE';

export const VOYAGE_PAGE_LOADED = 'VOYAGE_PAGE_LOADED';
export const SUBMIT_VOYAGE = 'SUBMIT_VOYAGE';
export const DELETE_VOYAGE = 'DELETE_VOYAGE';
export const SET_EDIT_VOYAGE = 'SET_EDIT_VOYAGE';
export const EDIT_VOYAGE = 'EDIT_VOYAGE';

export const RESERVATION_PAGE_LOADED = 'RESERVATION_PAGE_LOADED';
export const SUBMIT_RESERVATION = 'SUBMIT_RESERVATION';
export const DELETE_RESERVATION = 'DELETE_RESERVATION';
export const SET_EDIT_RESERVATION = 'SET_EDIT_RESERVATION';
export const EDIT_RESERVATION = 'EDIT_RESERVATION';