export const USER_PAGE_LOADED = 'USER_PAGE_LOADED';
export const SUBMIT_USER = 'SUBMIT_USER';
export const DELETE_USER = 'DELETE_USER';
export const SET_EDIT_USER = 'SET_EDIT_USER';
export const EDIT_USER = 'EDIT_USER';

export const AGENCE_PAGE_LOADED = 'AGENCE_PAGE_LOADED';
export const SUBMIT_AGENCE = 'SUBMIT_AGENCE';
export const DELETE_AGENCE = 'DELETE_AGENCE';
export const SET_EDIT_AGENCE = 'SET_EDIT_AGENCE';
export const EDIT_AGENCE = 'EDIT_AGENCE';

export const BON_PAGE_LOADED = 'BON_PAGE_LOADED';
export const SUBMIT_BON = 'SUBMIT_BON';
export const DELETE_BON = 'DELETE_BON';
export const SET_EDIT_BON = 'SET_EDIT_BON';
export const EDIT_BON = 'EDIT_BON';

export const CLIENT_PAGE_LOADED = 'CLIENT_PAGE_LOADED';
export const SUBMIT_CLIENT = 'SUBMIT_CLIENT';
export const DELETE_CLIENT = 'DELETE_CLIENT';
export const SET_EDIT_CLIENT = 'SET_EDIT_CLIENT';
export const EDIT_CLIENT = 'DIT_CLIENT';

export const DEVIS_PAGE_LOADED = 'DEVIS_PAGE_LOADED';
export const SUBMIT_DEVIS = 'SUBMIT_DEVIS';
export const DELETE_DEVIS = 'DELETE_DEVIS';
export const SET_EDIT_DEVIS = 'SET_EDIT_DEVIS';
export const EDIT_DEVIS = 'EDIT_DEVIS';

export const EMPLOYE_PAGE_LOADED = 'EMPLOYE_PAGE_LOADED';
export const SUBMIT_EMPLOYE = 'SUBMIT_EMPLOYE';
export const DELETE_EMPLOYE = 'DELETE_EMPLOYE';
export const SET_EDIT_EMPLOYE = 'SET_EDIT_EMPLOYE';
export const EDIT_EMPLOYE = 'EDIT_EMPLOYE';

export const FACTURE_PAGE_LOADED = 'FACTURE_PAGE_LOADED';
export const SUBMIT_FACTURE = 'SUBMIT_FACTURE';
export const DELETE_FACTURE = 'DELETE_FACTURE';
export const SET_EDIT_FACTURE = 'SET_EDIT_FACTURE';
export const EDIT_FACTURE = 'EDIT_FACTURE';

export const FOURNISSEUR_PAGE_LOADED = 'FOURNISSEUR_PAGE_LOADED';
export const SUBMIT_FOURNISSEUR = 'SUBMIT_FOURNISSEUR';
export const DELETE_FOURNISSEUR = 'DELETE_FOURNISSEUR';
export const SET_EDIT_FOURNISSEUR = 'SET_EDIT_FOURNISSEUR';
export const EDIT_FOURNISSEUR = 'EDIT_FOURNISSEUR';

export const PASSAGER_PAGE_LOADED = 'PASSAGER_PAGE_LOADED';
export const SUBMIT_PASSAGER = 'SUBMIT_PASSAGER';
export const DELETE_PASSAGER = 'DELETE_PASSAGER';
export const SET_EDIT_PASSAGER = 'SET_EDIT_PASSAGER';
export const EDIT_PASSAGER = 'EDIT_PASSAGER';

export const PERMISSION_PAGE_LOADED = 'PERMISSION_PAGE_LOADED';
export const SUBMIT_PERMISSION = 'SUBMIT_PERMISSION';
export const DELETE_PERMISSION = 'DELETE_PERMISSION';
export const SET_EDIT_PERMISSION = 'SET_EDIT_PERMISSION';
export const EDIT_PERMISSION = 'EDIT_PERMISSION';

export const POSTE_PAGE_LOADED = 'POSTE_PAGE_LOADED';
export const SUBMIT_POSTE = 'SUBMIT_POSTE';
export const DELETE_POSTE = 'DELETE_POSTE';
export const SET_EDIT_POSTE = 'SET_EDIT_POSTE';
export const EDIT_POSTE = 'EDIT_POSTE';

export const PRODUIT_PAGE_LOADED = 'PRODUIT_PAGE_LOADED';
export const SUBMIT_PRODUIT = 'SUBMIT_PRODUIT';
export const DELETE_PRODUIT = 'DELETE_PRODUIT';
export const SET_EDIT_PRODUIT = 'SET_EDIT_PRODUIT';
export const EDIT_PRODUIT = 'EDIT_PRODUIT';

export const RESERVATION_PAGE_LOADED = 'RESERVATION_PAGE_LOADED';
export const SUBMIT_RESERVATION = 'SUBMIT_RESERVATION';
export const DELETE_RESERVATION = 'DELETE_RESERVATION';
export const SET_EDIT_RESERVATION = 'SET_EDIT_RESERVATION';
export const EDIT_RESERVATION = 'EDIT_RESERVATION';

export const REVUEDEPERFORMANCE_PAGE_LOADED = 'REVUEDEPERFORMANCE_PAGE_LOADED';
export const SUBMIT_REVUEDEPERFORMANCE = 'SUBMIT_REVUEDEPERFORMANCE';
export const DELETE_REVUEDEPERFORMANCE = 'DELETE_REVUEDEPERFORMANCE';
export const SET_EDIT_REVUEDEPERFORMANCE = 'SET_EDIT_REVUEDEPERFORMANCE';
export const EDIT_REVUEDEPERFORMANCE = 'EDIT_REVUEDEPERFORMANCE';

export const SOCIETE_PAGE_LOADED = 'SOCIETE_PAGE_LOADED';
export const SUBMIT_SOCIETE = 'SUBMIT_SOCIETE';
export const DELETE_SOCIETE = 'DELETE_SOCIETE';
export const SET_EDIT_SOCIETE = 'SET_EDIT_SOCIETE';
export const EDIT_SOCIETE = 'EDIT_SOCIETE';

export const STOCK_PAGE_LOADED = 'STOCK_PAGE_LOADED';
export const SUBMIT_STOCK = 'SUBMIT_STOCK';
export const DELETE_STOCK = 'DELETE_STOCK';
export const SET_EDIT_STOCK = 'SET_EDIT_STOCK';
export const EDIT_STOCK = 'EDIT_STOCK';

export const VEHICULE_PAGE_LOADED = 'VEHICULE_PAGE_LOADED';
export const SUBMIT_VEHICULE = 'SUBMIT_VEHICULE';
export const DELETE_VEHICULE = 'DELETE_VEHICULE';
export const SET_EDIT_VEHICULE = 'SET_EDIT_VEHICULE';
export const EDIT_VEHICULE = 'EDIT_VEHICULE';

export const VOYAGE_PAGE_LOADED = 'VOYAGE_PAGE_LOADED';
export const SUBMIT_VOYAGE = 'SUBMIT_VOYAGE';
export const DELETE_VOYAGE = 'DELETE_VOYAGE';
export const SET_EDIT_VOYAGE = 'SET_EDIT_VOYAGE';
export const EDIT_VOYAGE = 'DIT_VOYAGE';